# SPDX-FileCopyrightText: 2025 Max Mehl <https://mehl.mx>
#
# SPDX-License-Identifier: CC0-1.0

services:
  home-stream:
    image: ghcr.io/mxmehl/home-stream:latest
    container_name: home-stream
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /path/to/local/data:/media/data
      - ./config/config.yaml:/app/config.yaml
    mem_limit: 500m
