; SPDX-FileCopyrightText: 2025 Max Mehl <https://mehl.mx>
; SPDX-License-Identifier: CC0-1.0

; uwsgi configuration for local usage. Can be called with `uv run uwsgi --ini uwsgi.ini`
[uwsgi]
; Flask app
wsgi-file = home_stream/wsgi.py
callable = app
; requires config in the config folder
pyargv=config/config.yaml
; uwsgi options
http = localhost:8000
master = true
processes = 8
harakiri = 600
max-fd = 1024
http-keepalive = 30
lazy-apps = true
; disable logging
disable-logging = true
